### ISSUE TITLE
Failure to build project with Gradle 7.5.1 on Linux

### ISSUE THREAD

**Issue by bperry-mf** [SasanLabs/VulnerableApp#443]
**Describe the bug** + **To Reproduce**
Hi,
I am new to using gradlew and wanted to ask how to successfully build the VulnerableApp project. There are a few test errors that prevent the project from successfully building. Here is a copy of the build output:

./gradlew clean build

> Task :compileJava
Note: /opt/repos/tarballs/java/gradle/VulnerableApp-1.11.22/src/main/java/org/sasanlabs/service/vulnerability/rfi/UrlParamBasedRFI.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :compileTestJava
Note: /opt/repos/tarballs/java/gradle/VulnerableApp-1.11.22/src/test/java/org/sasanlabs/controller/exception/ControllerExceptionHandlerTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/repos/tarballs/java/gradle/VulnerableApp-1.11.22/src/test/java/org/sasanlabs/service/vulnerability/commandInjection/CommandInjectionTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test

SSRFVulnerabilityTest > getVulnerablePayloadLevel1(String, boolean, String) > org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel1(String, boolean, String)[5] FAILED
    java.net.ConnectException at SSRFVulnerabilityTest.java:64

SSRFVulnerabilityTest > getVulnerablePayloadLevel1(String, boolean, String) > org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel1(String, boolean, String)[6] FAILED
    java.net.ConnectException at SSRFVulnerabilityTest.java:64

SSRFVulnerabilityTest > getVulnerablePayloadLevel2(String, boolean, String) > org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel2(String, boolean, String)[5] FAILED
    java.net.ConnectException at SSRFVulnerabilityTest.java:84

SSRFVulnerabilityTest > getVulnerablePayloadLevel2(String, boolean, String) > org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel2(String, boolean, String)[6] FAILED
    java.net.ConnectException at SSRFVulnerabilityTest.java:84

SSRFVulnerabilityTest > getVulnerablePayloadLevel3(String, boolean, String) > org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel3(String, boolean, String)[5] FAILED
    java.net.ConnectException at SSRFVulnerabilityTest.java:104

SSRFVulnerabilityTest > getVulnerablePayloadLevel3(String, boolean, String) > org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel3(String, boolean, String)[6] FAILED
    java.net.ConnectException at SSRFVulnerabilityTest.java:104

SSRFVulnerabilityTest > getVulnerablePayloadLevel4(String, boolean, String) > org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel4(String, boolean, String)[5] FAILED
    java.net.ConnectException at SSRFVulnerabilityTest.java:124

SSRFVulnerabilityTest > getVulnerablePayloadLevel4(String, boolean, String) > org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel4(String, boolean, String)[6] FAILED
    java.net.ConnectException at SSRFVulnerabilityTest.java:124

SSRFVulnerabilityTest > getVulnerablePayloadLevel5(String, boolean, String) > org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel5(String, boolean, String)[6] FAILED
    java.net.ConnectException at SSRFVulnerabilityTest.java:144

103 tests completed, 9 failed, 2 skipped

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///opt/repos/tarballs/java/gradle/VulnerableApp-1.11.22/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 19m 14s
11 actionable tasks: 11 executed

I am unsure why the is an error message mentions Gradle 8.0 because I specificly specified the Gradle version with the command:
./gradlew wrapper --gradle-version 7.5.1

I was wondering what are the specific versions of Gradle and NodeJS necessary to build this project. I am running the following packages versions (according to ./gradlew --version and nm --version):
Gradle 7.5.1
Kotlin: 1.6.21
Groovy: 3.0.10
Ant: Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM: 1.8.0_282 (Azul Systems, Inc. 25.282-b08)
OS: Linux 3.10.0-1160.62.1.el7.x86_64 amd64
GNU nm version 2.27-44.base.el7_9.1

**Expected behavior**
Perform a successful build with Gradle 7.5.1. How would I get past the 9 failed tests?

**Comment by preetkaran20** [comment]
Hi @bperry-mf 

As you are using gradle wrapper the version is implicit and I am also running gradle version 7.5.1 in my local machine and it is working fine for me. 

In case you just want to play around and get unblocked, you can skip tests by running `gradle build -x test`
<img width="1399" alt="image" src="https://github.com/SasanLabs/VulnerableApp/assets/13570884/d6469cf5-3752-42e9-a07d-b24ecada8671">

My local configurations:
<img width="534" alt="image" src="https://github.com/SasanLabs/VulnerableApp/assets/13570884/de791469-ebf5-4b24-bd8c-f84b1ada4d18">


can you please check if you have done any change which caused this issue?
To verify, please run:
```
git checkout master
git reset --hard origin/master
./gradlew clean build
```
thanks,
Karan

**Comment by preetkaran20** [comment]
Also, can you please share the complete error log by running with `--debug` option.

**Comment by bperry-mf** [comment]
The provided git commands were performed before executing `./gradlew clean build --debug` (HEAD is currenlty pointing to commit id ecfe0a01f661a68b6c88cd7e5baac127df5d7da0), and the `--debug` build's output and error messages are attached.
[buildebugoutput.txt](https://github.com/SasanLabs/VulnerableApp/files/12373465/buildebugoutput.txt)
[buildebugerror.txt](https://github.com/SasanLabs/VulnerableApp/files/12373468/buildebugerror.txt)

I'm going to try `gradle build -x test` as well.

**Comment by 000panther** [comment]
Might be related to a network connection not being available? Unit tests should not do network calls imho - they could maybe be mocked? 

2023-08-17T13:07:21.595-0700 [DEBUG] [TestEventLogger] 
2023-08-17T13:07:21.595-0700 [DEBUG] [TestEventLogger] SSRFVulnerabilityTest > getVulnerablePayloadLevel5(String, boolean, String) > org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel5(String, boolean, String)[6] FAILED
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]     java.net.ConnectException: Connection timed out (Connection timed out)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at java.net.PlainSocketImpl.socketConnect(Native Method)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at java.net.Socket.connect(Socket.java:607)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:284)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerability.getGenericVulnerabilityResponseWhenURL(SSRFVulnerability.java:73)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerability.getVulnerablePayloadLevel5(SSRFVulnerability.java:159)
2023-08-17T13:07:21.596-0700 [DEBUG] [TestEventLogger]         at org.sasanlabs.service.vulnerability.ssrf.SSRFVulnerabilityTest.getVulnerablePayloadLevel5(SSRFVulnerabilityTest.java:144)

**Comment by preetkaran20** [comment]
This is fixed now. Thanks
